import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "@/styles/Home.module.scss"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export default function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>Innov Bros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.site}>
        <header className={styles.header}>
          <div className={styles.logoContainer}>
            <Link href="/">
              <Image
                src="/theinnovationbrothers-logo-trimmy.png"
                alt="innovbros logo"
                fill
              />
            </Link>
          </div>
          <div className={styles.menu}>
            <Link className={styles.card} href="/about">
              <h2 className={inter.className}>
                About <span className={styles.menuArrow}>-&gt;</span>
              </h2>
              {/* <p className={inter.className}>Who we are</p> */}
            </Link>

            <Link className={styles.card} href="/work">
              <h2 className={inter.className}>
                Work <span className={styles.menuArrow}>-&gt;</span>
              </h2>
              {/* <p className={inter.className}>Our projects</p> */}
            </Link>

            <Link className={styles.card} href="/contact">
              <h2 className={inter.className}>
                Contact <span className={styles.menuArrow}>-&gt;</span>
              </h2>
            </Link>
          </div>
        </header>

        <main className={styles.page}>{children}</main>

        <footer className={styles.footer}>
          <p>
            {`Copyright © ${new Date().getFullYear()} The Innovation Brothers`}
          </p>
          <p>{"All rights reserved."}</p>
        </footer>
      </div>
    </>
  )
}
