import Head from "next/head"
import Image from "next/image"
import styles from "@/styles/Home.module.scss"
import { Cross as Hamburger } from "hamburger-react"
import { useState } from "react"
import Link from "next/link"
import Menu from "./menu"

export default function Layout({ children }: any) {
  const [menuOpen, setMenuOpen] = useState(false)

  return (
    <>
      <Head>
        <title>Innov Bros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.site}>
        <header className={styles.header}>
          <div className={styles.logoContainer}>
            <Link href="/">
              <Image
                src="/theinnovationbrothers-logo-trimmy.png"
                alt="innovbros logo"
                fill
              />
            </Link>
          </div>

          <Menu />
          <div className={styles.hamburger}>
            <Hamburger
              distance="lg"
              size={48}
              rounded
              toggled={menuOpen}
              toggle={setMenuOpen}
            />
          </div>
        </header>

        {menuOpen ? (
          <Menu mobile />
        ) : (
          <main className={styles.page}>{children}</main>
        )}

        <footer className={styles.footer}>
          <p>
            {`Copyright © ${new Date().getFullYear()} The Innovation Brothers`}
          </p>
          <p>{"All rights reserved."}</p>
        </footer>
      </div>
    </>
  )
}
