import { WorkItem } from "../content/types"

export const warmupIntro: WorkItem = {
  title: "Introduction",
  author: "The Innovation Brothers",
  coverImage: "",
  description:
    "what made us make this list",
  content: [
    {
      type: "Paragraph",
      text: "Back in 2013 we started making our database of tools, methods and processes for creativity, design and innovation. Continuously in the making, the database already houses more than one thousand tools, methods and processes, distributed across twelve categories.",
    },
    {
      type: "Paragraph",
      text: "This section brings together a collection of 52 handpicked Warm-up energisers' tools and methods in a comics medium.",
    },
    {
      type: "Paragraph",
      text: "This medium is used because of its visual nature and permanence. Unlike traditional textbooks, comics show the information visually. And unlike other visual narratives, like video or animation, comics enable each reader to choose progress at their own rate. These characteristics of comics makes it an incredibly powerful information-sharing tool.",
    },
    {
      type: "Paragraph",
      text: "The illustrations were created by prompting an artificial intelligence (AI) with a written description of the desired output. The description included keywords and keyphrases describing the content to be illustrated. This AI used its algorithms to generate a set of unique images based on these parameters.",
    },
    {
      type: "Paragraph",
      text: "Warm-up energisers are a critical part of collaboration and innovation. The same way that athletes always warm up to boost performance and prevent injuries, Warm-up energisers are a systematic and strategic way to prepare everyone for success by encouraging their creative, empathetic and synergetic performance.",
    },
    {
      type: "Paragraph",
      text: "Warm-up energisers help in creating the necessary space for collaboration. They are set up for everyone to be on the same page and with the mindset and brainspace for the working session ahead. Additionally, warm-up energisers enable the practice of critical skills that build the psychological safety and creative confidence of people. This makes them participate, take risks, challenge their biases, and be more open to creative ideas.",
    },
    {
      type: "Paragraph",
      text: "These tools and methods will help you coach and inspire those around you, as well as advance your own innovation efforts. All the materials in this section are designed to be practical and straightforward to use. The Warm-up energisers can be mixed and matched to create the best experience for any session, meeting or workshop. Ready-to-use templates and worksheets for the tools and methods are attached to print-out or use with your preferred software.",
    },
    {
      type: "Paragraph",
      text: "The Warm-up energisers are divided in four parts. Part one, Introduce Each Other, comprises 17 methods and tools to promote people to get to know each other. Part two, Encourage Creativity, contains 16 methods and tools to encourage creative thinking. Part three, Team Dynamics, includes 10 methods and tools to strengthen collaboration. And part four, Boost Communication, consists of 9 methods and tools to reinforce  listening and empathy.",
    },
    {
      type: "Paragraph",
      text: "Here we show the set of 19 illustrations generated by the AI with the corresponding prompt. To these prompts was added the common paramenter 'continuous line drawing' for a coherent design language throughout the book.",
    },
    {
      type: "Image",
      image: "19-warmup-imgs.jpg",
      alt: "AI-generated illustrations",
    },
    {
      type: "Link",
      text: "Back to Warm-up Energisers",
      url: "../toolkit/warmup",
    },
  ],
}
